apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: "postgresql://test:test@postgres-service:5432/test?schema=public"
  JWT_SECRET: "c=,d-<^w7[su8>G3;TIvUrken@)*2HVqlB!+_b./NF5?'Eg:"

---

# Backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkasa-backend
  template:
    metadata:
      labels:
        app: linkasa-backend
    spec:
      containers:
        - name: linkasa-backend
          image: qualifnw251.azurecr.io/linkasa-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30

---

# Frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkasa-frontend
  template:
    metadata:
      labels:
        app: linkasa-frontend
    spec:
      containers:
        - name: linkasa-frontend
          image: qualifnw251.azurecr.io/linkasa-frontend:v1
          ports:
            - containerPort: 80