# Backend

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP 
  selector:
    app: linkasa-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

#Frontend

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer 
  selector:
    app: linkasa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80